name: Continuous Integration
run-name: ${{ github.actor }} is testing out main branch push.

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      # Check out local repo
      - name: Check out main repository
        uses: actions/checkout@v3

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Sanity check
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Update Pip
        run: |
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r ./project/requirements.txt

      # Run Test.py
      - name: Run tests
        id: run_tests
        run: |
          chmod +x project/tests.sh
          ./project/tests.sh
        #working-directory: ./project
